### ISSUE TITLE
Can't see my Bluetooth devices

### ISSUE THREAD

**Issue by monza258** [paolotremadio/homebridge-automation-bluetooth-presence#1]
Hey, I can't see all my Bluetooth devices. 

`pi@raspberrypi2:~ $ sudo npm run detect-devices
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-11T20_11_10_307Z-debug.log`

**Comment by paolotremadio** [comment]
Hi, thanks for your feedback. I've updated the README to make it clearer 😊 

Let me know if it works for you.

**Comment by monza258** [comment]
Wow. Thank you. 

It Works. 

`Cpi@raspberrypi2:~ $ sudo automation-bt-detect-devices
Scanning for devices... [Hit Ctrl+C to stop]
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: 16bd68ab61af	Signal: 70%	Name: undefined
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: ea1240f90a7f	Signal: 34%	Name: Eve Energy 6CCD
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: 086698d10e09	Signal: 100%	Name: undefined
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: 27286d485006	Signal: 26%	Name: undefined
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: 4a18fafac0ed	Signal: 88%	Name: undefined
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: ca314e091f6d	Signal: 100%	Name: Eve Energy 4101
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: e1253584ae8c	Signal: 54%	Name: Eve Thermo 0379
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: c1e0ac2e0b4d	Signal: 30%	Name: Eve Thermo 426E
[Wed Sep 12 2018 19:28:46 GMT+0200 (CEST)] ID: f3903706c236	Signal: 8%	Name: Eve Door 6155
[Wed Sep 12 2018 19:28:47 GMT+0200 (CEST)] ID: 044bedb0a1db	Signal: 40%	Name: undefined
[Wed Sep 12 2018 19:28:47 GMT+0200 (CEST)] ID: c5853b30d314	Signal: 48%	Name: Eve Energy A72E
[Wed Sep 12 2018 19:28:47 GMT+0200 (CEST)] ID: e06705a2eb49	Signal: 8%	Name: Eve Weather C4E7
[Wed Sep 12 2018 19:28:47 GMT+0200 (CEST)] ID: 54c9df6c80e0	Signal: 96%	Name: LM5766
[Wed Sep 12 2018 19:28:49 GMT+0200 (CEST)] ID: ef1c6f1975a2	Signal: 62%	Name: Eve Thermo 849D
[Wed Sep 12 2018 19:28:51 GMT+0200 (CEST)] ID: 7d4d0d71c3b9	Signal: 38%	Name: undefined
[Wed Sep 12 2018 19:28:52 GMT+0200 (CEST)] ID: 7065fa30b0f6	Signal: 40%	Name: undefined
[Wed Sep 12 2018 19:28:54 GMT+0200 (CEST)] ID: 38c70a808269	Signal: 24%	Name: LinkDesk
[Wed Sep 12 2018 19:29:00 GMT+0200 (CEST)] ID: d550c02aab91	Signal: 22%	Name: Eve Thermo A565
[Wed Sep 12 2018 19:29:00 GMT+0200 (CEST)] ID: 5a14ecd79f07	Signal: 16%	Name: undefined
[Wed Sep 12 2018 19:29:02 GMT+0200 (CEST)] ID: 54d27276bf51	Signal: 22%	Name: Nuki_0876BF51
[Wed Sep 12 2018 19:29:14 GMT+0200 (CEST)] ID: 509976cccbb5	Signal: 2%	Name: undefined
[Wed Sep 12 2018 19:29:24 GMT+0200 (CEST)] ID: 457179a55761	Signal: 86%	Name: undefined
[Wed Sep 12 2018 19:30:03 GMT+0200 (CEST)] ID: 441a05244286	Signal: 6%	Name: undefined
[Wed Sep 12 2018 19:30:39 GMT+0200 (CEST)] ID: d4619d1b7aaf	Signal: 10%	Name: undefined
[Wed Sep 12 2018 19:32:32 GMT+0200 (CEST)] ID: 5352007c27fe	Signal: 14%	Name: undefined
[Wed Sep 12 2018 19:37:03 GMT+0200 (CEST)] ID: 6b2bc2eaadb1	Signal: 6%	Name: undefined
[Wed Sep 12 2018 19:42:03 GMT+0200 (CEST)] ID: 5916a27144c5	Signal: 40%	Name: undefined
[Wed Sep 12 2018 19:45:59 GMT+0200 (CEST)] ID: 74cdbdb61121	Signal: 4%	Name: undefined
[Wed Sep 12 2018 19:50:50 GMT+0200 (CEST)] ID: 74c132d612a1	Signal: 88%	Name: undefined
[Wed Sep 12 2018 19:51:06 GMT+0200 (CEST)] ID: 5db1257caa25	Signal: 0%	Name: undefined
[Wed Sep 12 2018 19:51:26 GMT+0200 (CEST)] ID: 633708572a81	Signal: 10%	Name: undefined
[Wed Sep 12 2018 19:53:02 GMT+0200 (CEST)] ID: 40e0d78854f6	Signal: 4%	Name: undefined`

But, it does not trigger in HomeKit.

`{
            "accessory": "AutomationBluetoothPresence",
            "name": "iPhone 10",
            "deviceId": "783c4ebc68df",
            "gracePeriod": 600
        }`

**Comment by paolotremadio** [comment]
Have you captured the ID from the raspberrypi?

Also, try to unlock the iPhone, does it get detected?

**Comment by monza258** [comment]
yes, I have taken the id that was shown to me. you can see below in my comment.

Even unlocking does not help.

**Comment by paolotremadio** [comment]
Can you please send me the full output of Homebridge? I'd like to check if the plugin has been loaded and  if it is reporting any errors.

**Comment by monza258** [comment]
full Output?

`Sep 13 19:33:52 raspberrypi2 homebridge[7510]: [2018-9-13 19:33:52] Loaded plugin: homebridge-automation-bluetooth-presence
Sep 13 19:33:52 raspberrypi2 homebridge[7510]: [2018-9-13 19:33:52] Registering accessory 'homebridge-automation-bluetooth-presence.AutomationBluetoothPresence'
Sep 13 19:33:52 raspberrypi2 homebridge[7510]: [2018-9-13 19:33:52] ---`



`Sep 13 19:33:56 raspberrypi2 homebridge[7510]: [2018-9-13 19:33:56] [Device1] Initializing AutomationBluetoothPresence accessory...
Sep 13 19:33:56 raspberrypi2 homebridge[7510]: [2018-9-13 19:33:56] [Device2i6] Initializing AutomationBluetoothPresence accessory...`

**Comment by paolotremadio** [comment]
I'm investigating the issue but I cannot reproduce it. It works perfectly when running it on Mac. But I've also noticed that this plugin is using a fair amount of CPU so I'll work on restructuring it as soon as I can.

**Comment by paolotremadio** [comment]
I've just published a new version. Please install it.

Run the `sudo automation-bt-detect-devices` and please paste the row regarding your iPhone. 

I will also need:
- The updated snippet from your homebridge config
- How are you running homebridge? (Specifiy the command and any params passed to it)
- Is it running on the same Raspberry PI as the one you've used to run the detect devices?
- What model of Raspberry PI it is?

**Comment by monza258** [comment]
Update:

`pi@raspberrypi2:~ $ sudo npm install --unsafe-perm homebridge-automation-bluetooth-presence -g
/usr/local/bin/automation-bt-detect-devices -> /usr/local/lib/node_modules/homebridge-automation-bluetooth-presence/bin/automation-bt-detect-devices
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/homebridge-automation-bluetooth-presence/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-automation-bluetooth-presence@0.2.0
added 9 packages from 4 contributors and updated 6 packages in 21.251s`

Homebridge ist Running as systemd:
sudo systemctl start homebridge

Same PI
I have a PI3

**Comment by monza258** [comment]
Doesn’t work. 😢 

No trigger in HomeKit.

**Comment by paolotremadio** [comment]
I’ve managed to reproduce it. It looks like an issue with the RPI controller. I’ll try to debug it and I’ll keep you posted. Also, are you running homebridge as sudo?

**Comment by paolotremadio** [comment]
Just released a new version. Please install it and let me know if it fixes the issue

**Comment by monza258** [comment]
Sorry about it. It doesn't work now. No Triggers in HomeKit. 
I also see nothing in my LOG file, which triggers something there.

I Start my PI with command:
sudo systemctl start homebridge

**Comment by paolotremadio** [comment]
Can you check which user is homebridge running?

Try something like:
ps -aux | grep node 

Or:
ps -aux | grep homebridge

**Comment by monza258** [comment]
pi@raspberrypi2:~ $ ps -aux | grep node
pi       20060  0.0  0.0   4344   560 pts/0    S+   21:03   0:00 grep --color=auto node
pi@raspberrypi2:~ $ ps -aux | grep homebridge
root       505  1.6  4.7 126292 45324 ?        Ssl  20:39   0:23 homebridge
root       506  4.1  8.0 1174192 76036 ?       Ssl  20:39   1:00 homebridge
pi       12867  3.7  9.7 174768 92608 ?        Ssl  20:52   0:26 homebridge
pi       13087  1.0  4.9 149724 46724 ?        Sl   20:52   0:07 homebridge-config-ui-x
pi       20151  0.0  0.0   4344   580 pts/0    S+   21:03   0:00 grep --color=auto homebridge

**Comment by paolotremadio** [comment]
You have 3 instances of homebridge, that’s really strange. How have you installed it on the RPI? Can you send me the init script?

**Comment by monza258** [comment]
https://forum.smartapfel.de/forum/thread/910-homebridge-instanzen-anlegen/?postID=17039#post17039

That's what I wanted. This is how homebridge runs more stable.

**Comment by paolotremadio** [comment]
Please:
- stop homebridge
- killall -9 homekit
- start again
- ps -aux | grep homebridge

And paste the result. Also, what’s the full path of your config file?

**Comment by monza258** [comment]
pi@raspberrypi2:~ $ ps -aux | grep homebridge
root     20754  9.3  4.0 132880 38664 ?        Ssl  21:56   0:05 homebridge
root     20786 39.8 11.0 1198032 104960 ?      Ssl  21:56   0:20 homebridge
pi       22150  0.0  0.0   4344   540 pts/0    S+   21:57   0:00 grep --color=auto homebridge

i have more config.json but there is my Main Instance
/var/homebridge/config.json

**Comment by paolotremadio** [comment]
Do you have multiple instances running at the same time?

**Comment by monza258** [comment]
Yes. 

-GOOD NEWS-
I have inserted the plugin into another running instance. Now the plugin works and the trigger has been triggered in homekit. User pi and root Problem?

**Comment by paolotremadio** [comment]
Brilliant! I’ve found out today that homebridge must be run as root on Linux, it it won’t have access to Bluetooth. So maybe you were running it as non-root (pi) which would stop it from running correctly. 

I’m glad it is all solved, thanks for helping me out improving this plugin!

**Comment by monza258** [comment]
I can not define which of the displayed devices my iPhones are.
I always only see name: undefined.

If I enter these in my config, this triggers in Homekit also. Later, the ID no longer exists and does not trigger anymore.

**Comment by paolotremadio** [comment]
Was it not working? 😊

Ok, help me debug it: still on linux/rpi? also, can you please send me one (or more if possible) IDs of your devices?

**Comment by monza258** [comment]
Continue RPI. I only see "undefined" and some Elgato Eve energy. I can not tell what the device is my iphone or my girlfriend. I have some id's registered in my config.
Do you want the current id's I have in my config? Or who are in the listing?

**Comment by paolotremadio** [comment]
So, on Linux the ID should be the MAC address of your phone (without the “:”). To get your MAC address go on your iPhone to Settings > General > About. The ID is under “Bluetooth”. Do you get that ID from the discover devices of my plugin?

**Comment by monza258** [comment]
If I run automation-bt-detect-devices, I don’t see my device Id. Only when I go to settings in my phone. 

When I put inside my Id: d0d2b0670c79 it will not entered. 

So didn’t work.

**Comment by monza258** [comment]
So look step by step:

I run:  sudo automation-bt-detect-devices
Then I can see all ids:
[Fri Sep 28 2018 07:54:59 GMT+0200 (CEST)] ID: ee:c0:57:39:04:04	Signal: 48%	Name: Eve Energy 1453
[Fri Sep 28 2018 07:54:59 GMT+0200 (CEST)] ID: 08:66:98:d1:0e:09	Signal: 100%	Name: undefined
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 29:51:67:5c:18:2d	Signal: 18%	Name: undefined
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 54:c9:df:6c:80:e0	Signal: 100%	Name: LM5766
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 04:d4:82:6f:3d:40	Signal: 100%	Name: undefined
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 61:bf:2f:0b:e0:c3	Signal: 72%	Name: undefined
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: ea:12:40:f9:0a:7f	Signal: 40%	Name: Eve Energy 6CCD
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 7c:3b:fa:ec:f2:28	Signal: 38%	Name: undefined
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: c5:85:3b:30:d3:14	Signal: 32%	Name: Eve Energy A72E
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 04:4b:ed:b0:a1:db	Signal: 34%	Name: undefined
[Fri Sep 28 2018 07:55:00 GMT+0200 (CEST)] ID: 69:61:9c:94:60:b4	Signal: 32%	Name: undefined
[Fri Sep 28 2018 07:55:01 GMT+0200 (CEST)] ID: ef:1c:6f:19:75:a2	Signal: 38%	Name: Eve Thermo 849D
[Fri Sep 28 2018 07:55:03 GMT+0200 (CEST)] ID: 54:d2:72:76:bf:51	Signal: 34%	Name: Nuki_0876BF51
[Fri Sep 28 2018 07:55:04 GMT+0200 (CEST)] ID: e1:25:35:84:ae:8c	Signal: 52%	Name: Eve Thermo 0379
[Fri Sep 28 2018 07:55:04 GMT+0200 (CEST)] ID: c1:e0:ac:2e:0b:4d	Signal: 16%	Name: Eve Thermo 426E
[Fri Sep 28 2018 07:55:11 GMT+0200 (CEST)] ID: f3:90:37:06:c2:36	Signal: 32%	Name: Eve Door 6155
[Fri Sep 28 2018 07:55:12 GMT+0200 (CEST)] ID: d5:50:c0:2a:ab:91	Signal: 10%	Name: Eve Thermo A565

I can't see the device id of my iPhone.
Here are the Conig of my iPhone:
"accessory": "AutomationBluetoothPresence",
                "name": "Device1",
                "deviceId": "d0d2b0670c79",
                "gracePeriod": 600

Here my LOG
[2018-9-28 07:52:50] [Device1] Looking for Bluetooth devices

So it will not Trigger in HomeKit

**Comment by paolotremadio** [comment]
I'm really confused now. Was it not working? what has changed?

**Comment by monza258** [comment]
Don’t working. I have it delete from my PI.
