### ISSUE TITLE
How to Remove plugin

### ISSUE THREAD

**Issue by PaulBartelings** [paolotremadio/homebridge-automation-bluetooth-presence#15]
Hi after Remove the plugin i have this error,

Failed to parse plugin "homebridge-automation-bluetooth-presence": ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge-automation-bluetooth-presence/package.json'

Can you plz help me to Remove the rest of it .

**Comment by paolotremadio** [comment]
How have you removed it?

**Comment by PaulBartelings** [comment]
I did the uninstall from homebridge

**Comment by paolotremadio** [comment]
> I did the uninstall from homebridge

Yes, but how? What command have you used to remove it?

**Comment by PaulBartelings** [comment]
I used the uninstall button of the Homebridge Config UI X.

**Comment by paolotremadio** [comment]
> I used the uninstall button of the Homebridge Config UI X.

I have no idea how that work. Please open an issue on the config ui.

**Comment by PaulBartelings** [comment]
can you plz give me the Command for the commandpromd

**Comment by donavanbecker** [comment]
@PaulBartelings Run 

`sudo rm -R /usr/local/lib/node_modules/homebridge-automation-bluetooth-presence/` 

that will take care of this plugin issue.
